
Possible known issues:

1. When running the Crossmapper on Mac machine in conda environment, users can possibly encounter the following error:

dyld: Library not loaded: @rpath/libcrypto.1.0.0.dylib
  Referenced from: /Users/hrant/anaconda3/envs/crossmapper_v1/bin/wgsim
  Reason: image not found
  
 To fix the issue, outside of the conda environment run:
 
brew update
brew install openssl
ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/
ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/


2. When running the Crossampper in Sun Grid Engine managed clusters using conda environment, users can possibly encounter the following error:
wgsim: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory.

To fix the isse, inside the conda environemnt run:

conda install -c conda-forge ncurses


3. If after installing crossmapper with conda 4.11.0 (and potentially with other version), the command crossmapper -h outputs a long error ending with with "from _ctypes import Union, Structure, Array
ImportError: libffi.so.6: cannot open shared object file: No such file or directory", then please refer the following thread https://github.com/Gabaldonlab/crossmapper/issues/5

If the errors persist, please open an Issue in our GitHub.
